{"uuid": "42205114-7d10-4c72-bccb-1c3fcd93d74f", "children": ["0811a3ab-cadc-4d69-bfff-22a7e21fbe57"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "Exception: 无该校验方式：no_check\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 28, in login\n    api_send_check(request.param, case_dict, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/api_send_check.py\", line 33, in api_send_check\n    check_result.check_result(test_name, check_data, code, data, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/check_result.py\", line 128, in check_result\n    raise Exception(\"无该校验方式：{}\".format(case[\"check_type\"]))\n"}, "steps": [{"name": "POST请求接口", "status": "passed", "attachments": [{"name": "请求接口：", "source": "fcc58d3f-05b8-46ab-b4f2-9d15b80c3d8f-attachment.attach"}, {"name": "用例描述：", "source": "6bd30093-8518-422d-b831-78223385893a-attachment.attach"}, {"name": "请求地址", "source": "ba2795f7-9be0-4a76-bb6b-b889bddc8e54-attachment.attach"}, {"name": "请求头", "source": "6882e787-f71a-474f-b1a5-451fc464f9b4-attachment.attach"}, {"name": "请求参数", "source": "168907a6-bdfa-486f-a712-72cfa85fb2e9-attachment.attach"}], "start": 1617289781767, "stop": 1617289781769}, {"name": "不校验结果", "status": "passed", "start": 1617289781982, "stop": 1617289781982}], "start": 1617289781763, "stop": 1617289781982}], "start": 1617289781763, "stop": 1617289782075}