{"uuid": "a5ee101e-8ee6-4158-970a-0218b323a83f", "children": ["03bfb946-65cf-4f64-b0d5-ee7c7d001e28"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "KeyError: 'is_run'\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 28, in login\n    api_send_check(request.param, case_dict, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/api_send_check.py\", line 24, in api_send_check\n    if case_data['is_run'] is not False:\n"}, "start": 1617289344683, "stop": 1617289344687}], "start": 1617289344683, "stop": 1617289344777}