{"uuid": "cbf7deef-3af2-4b0a-94b2-d82b67e091b4", "children": ["86017aa5-2e09-48cf-88d5-ac8cbedbb826"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "Exception: 无该校验方式：no_check\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 28, in login\n    api_send_check(request.param, case_dict, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/api_send_check.py\", line 33, in api_send_check\n    check_result.check_result(test_name, check_data, code, data, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/check_result.py\", line 128, in check_result\n    raise Exception(\"无该校验方式：{}\".format(case[\"check_type\"]))\n"}, "steps": [{"name": "POST请求接口", "status": "passed", "attachments": [{"name": "请求接口：", "source": "2ccb52e2-f350-40c3-8d27-f948f0f42cd9-attachment.attach"}, {"name": "用例描述：", "source": "f657d985-fa37-445e-ada6-df1ea33f26e1-attachment.attach"}, {"name": "请求地址", "source": "8e9e2777-777c-4653-b85e-c9e9a1abc65d-attachment.attach"}, {"name": "请求头", "source": "fcf61466-0e18-4fd3-9b67-6b6e169fb62a-attachment.attach"}, {"name": "请求参数", "source": "6fc5dd20-0b48-4a87-9b66-e68008dd9118-attachment.attach"}], "start": 1617289727943, "stop": 1617289727945}, {"name": "不校验结果", "status": "passed", "start": 1617289728107, "stop": 1617289728107}], "start": 1617289727941, "stop": 1617289728107}], "start": 1617289727941, "stop": 1617289728175}