{"uuid": "b5261bb1-e2ca-4578-9a2f-23d0f044bed1", "children": ["36990e07-a3d6-4db9-b438-58ee5c02e94f"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "Exception: 无该校验方式：no_check\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 28, in login\n    api_send_check(request.param, case_dict, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/api_send_check.py\", line 33, in api_send_check\n    check_result.check_result(test_name, check_data, code, data, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/check_result.py\", line 129, in check_result\n    raise Exception(\"无该校验方式：{}\".format(case[\"check_type\"]))\n"}, "steps": [{"name": "POST请求接口", "status": "passed", "attachments": [{"name": "请求接口：", "source": "8b845f74-7ee3-4427-b030-69e9dbcb727b-attachment.attach"}, {"name": "用例描述：", "source": "cb8cf1bd-fc86-4bef-afb0-5df19d4a9d77-attachment.attach"}, {"name": "请求地址", "source": "2f592652-b8a7-42a4-b534-cedce1c578d6-attachment.attach"}, {"name": "请求头", "source": "b80fe28a-3245-46cb-831f-f9a0f2177ecd-attachment.attach"}, {"name": "请求参数", "source": "56d252b0-4e95-4994-a2d3-37fe5913c51a-attachment.attach"}], "start": 1617514045194, "stop": 1617514045198}, {"name": "不校验结果", "status": "passed", "start": 1617514045689, "stop": 1617514045689}], "start": 1617514045189, "stop": 1617514045689}], "start": 1617514045189, "stop": 1617514045974}