{"uuid": "9bafd705-ebf1-4a1f-be18-cc98841bf3fd", "children": ["9800df1a-df77-420c-8ac3-ebb960cb5786", "2ff15837-a616-4969-b5a2-b98395bc1254", "2f7b9d05-4867-47dc-82d7-97090a8ba985", "47215c0a-eb22-4f7f-8b2b-ab7ac1a6e54a", "c62255cd-909e-4b65-bb9a-79e5a3c417f4", "258f81a1-60ef-45b9-a730-f3102aee4cfb", "09be4203-d7b5-4dad-9987-7a7b8841288a", "367a1fac-4e6b-427c-a589-97455e70e84e", "a5fb1666-63aa-481e-bb2c-d3f3fe184807", "764b34fd-f9e7-48b7-a5c3-c9f77b37e726", "e9f1493a-6466-43e4-b07b-fab532e6ea91", "0ae49d81-34ee-45dd-84c6-b1a9e63ae504", "5f01306e-7dd4-4a46-b47c-ecf81e24d6af", "715594a3-05f4-4784-9af4-44249dd643f2", "f9e67417-b113-4168-af9b-e15771988cd0", "c66f8509-b1bc-4c7c-b008-6c58e3150041", "3e27977e-0278-425b-ae84-167e6aa3073a", "b57888f9-45ff-41e9-9d9a-712cad19f635", "185b05ce-2e2b-455d-8f27-a202690b7343"], "befores": [{"name": "setup_env", "status": "broken", "statusDetails": {"message": "AttributeError: module 'allure' has no attribute 'environment'\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 22, in setup_env\n    allure.environment(测试环境=\"测试环境\", hostName=Host[\"HOST2\"], 执行人=\"安琪\", 测试项目=\"m站线上接口测试\")\n"}, "start": 1617806989814, "stop": 1617806989814}], "start": 1617806989814, "stop": 1617806990041}