{"uuid": "2c4f996a-3e28-4b89-a1ef-344038eb07e7", "children": ["6123ea41-b67d-4a55-9a33-d7e6c42486d3"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "Exception: 无该校验方式：no_check\n", "trace": "  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/nali/anaconda3/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/nali/AutoApiTest/conftest.py\", line 28, in login\n    api_send_check(request.param, case_dict, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/api_send_check.py\", line 33, in api_send_check\n    check_result.check_result(test_name, check_data, code, data, case_path, relevance)\n  File \"/Users/nali/AutoApiTest/common/unit/check_result.py\", line 128, in check_result\n    raise Exception(\"无该校验方式：{}\".format(case[\"check_type\"]))\n"}, "steps": [{"name": "POST请求接口", "status": "passed", "attachments": [{"name": "请求接口：", "source": "f8c7170c-028d-4598-b7da-7c6a4ce4cabe-attachment.attach"}, {"name": "用例描述：", "source": "3856f492-b9d2-4b3d-a9a4-95bebd54e8a8-attachment.attach"}, {"name": "请求地址", "source": "ae18994d-f926-4ea8-b2a4-bcfeed17b7b3-attachment.attach"}, {"name": "请求头", "source": "a70d5d80-3513-416d-8cb6-56623cbfbf1b-attachment.attach"}, {"name": "请求参数", "source": "781955cb-d597-4fa3-a94d-e3472e67c7ee-attachment.attach"}], "start": 1617289580031, "stop": 1617289580033}, {"name": "不校验结果", "status": "passed", "start": 1617289580391, "stop": 1617289580391}], "start": 1617289580029, "stop": 1617289580391}], "start": 1617289580029, "stop": 1617289580420}